module Bridge
  autoload :Game, File.expand_path('../bridge/game', __FILE__)
  autoload :Card, File.expand_path('../bridge/card', __FILE__)
  autoload :Strain, File.expand_path('../bridge/strain', __FILE__)
  autoload :Rank, File.expand_path('../bridge/rank', __FILE__)
  autoload :Hand, File.expand_path('../bridge/hand', __FILE__)
  autoload :Player, File.expand_path('../bridge/player', __FILE__)
  autoload :Handler, File.expand_path('../bridge/handler', __FILE__)
  autoload :Pbn, File.expand_path('../bridge/pbn/pbn', __FILE__)
  autoload :PbnSubgame, File.expand_path('../bridge/pbn/pbn_subgame', __FILE__)
  autoload :PbnGameParser, File.expand_path('../bridge/pbn/pbn_game_parser', __FILE__)
  autoload :PbnSubgameMarshaller, File.expand_path('../bridge/pbn/pbn_subgame_marshaller', __FILE__)
  autoload :PbnParserState, File.expand_path('../bridge/pbn/parser_states/pbn_parser_state', __FILE__)
  autoload :BeforeFirstTag, File.expand_path('../bridge/pbn/parser_states/before_first_tag', __FILE__)
  autoload :BeforeTagName, File.expand_path('../bridge/pbn/parser_states/before_tag_name', __FILE__)
end
